name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}

      - name: Add dokku remote
        run: git remote add dokku dokku@devops.s14.local:wordpress-app

      - name: Push to Dokku
        id: dokku-deploy
        run: |
          set -e
          if ! git push dokku main; then
            echo "Deployment failed! Rolling back to previous release..."
            ssh -o StrictHostKeyChecking=no dokku@devops.s14.local "dokku releases:revert wordpress-app \$(dokku releases:list wordpress-app --no-truncate | sed -n '3p' | awk '{print \$1}')"
            exit 1
          fi

    